(ns euphony.commands.parser-test
  (:require [clojure.test :as t]
            [euphony
             [queries :as q]
             [test-system :as ts]]
            [euphony.commands.parser :refer :all]
            [euphony.protocols.conn :as pc]
            [euphony.structs.label :as l]
            [euphony.utils.log :as log]))

(t/use-fixtures :once ts/with-results ts/with-conn-after-results)

                                        ; CONSTRUCTORS

(t/deftest can-compute-priority
  (t/are [i entry, output] (= (priority i entry) output)
    0 ["" [[:w "android" #{:name :platform}]]]                                , [0, 1]
    1 ["" [[:w "android" #{:name :platform :information}]]]                   , [1, 2]
    2 ["" [[:w "android" #{:platform}] [:w "dogwin" #{:name}]]]               , [2, 0]
    3 ["" [[:w "android" #{:platform}] [:w "dogwin" #{:name type}]]]          , [3, 1]
    4 ["" [[:w "android" #{:platform}] [:s "/"] [:w "dogwin" #{:name}]]]      , [4, 0]
    5 ["" [[:w "android" #{:platform}] [:s "/"] [:w "dogwin" #{:name :type}]]], [5, 1]))

(t/deftest can-make-pqueue
  (t/is (= (pqueue (partial priority 0) ["android.trojan", "adware:/dogwin.1", "generic-a.kcloud [trj]"])
           '{["android.trojan"
              [[:w "android" #{:I :P :T :N}] [:s "."] [:w "trojan" #{:I :P :T :N}]]]
             [0 6],
             ["adware:/dogwin.1"
              [[:w "adware" #{:I :P :T :N}] [:s ":/"] [:w "dogwin" #{:I :P :T :N}]
               [:s "."] [:w "1" #{:I}]]]
             [0 6],
             ["generic-a.kcloud [trj]"
              [[:w "generic" #{:I :P :T :N}] [:s "-"] [:w "a" #{:I}] [:s "."]
               [:w "kcloud" #{:I :P :T :N}] [:s " ["] [:w "trj" #{:I :P :T :N}] [:s "]"]]]
             [0 9]})))

                                        ; MAIN FUNCTIONS

(t/deftest can-parse-labels
  (let [results ts/*results*
        labels (map second results)
        [conn mapping] (log/with-level :info (parse ts/*conn-after-results* labels))
        label-fields (fn [mapping l] (->> (get mapping l) (filter l/token-word?) (map l/token-fields)))]
    (t/is (= (count (q/db>labels-with-unknown-fields-pattern (pc/db ts/*conn-after-results*))) 149))
    (t/is (= (count (q/db>labels-with-unknown-fields-pattern (pc/db conn))) 17))
    (t/are [label, fields] (= (label-fields mapping label) fields)
      "a variant of android/adware.adswo.b" [#{:I} #{:I} #{:I} #{:P} #{:T} #{:N} #{:I}]
      "a variant of android/beanbot.a" [#{:I} #{:I} #{:I} #{:P} #{:N} #{:I}]
      "adware.multiads!550a" [#{:T} #{:I :P :N} #{:I :P}]
      "and/spyware-smsspy" [#{:P} #{:T} #{:N}]
      "andr.pjapps-22" [#{:P} #{:N} #{:I}]
      "andr.trojan.pjapps-1" [#{:P} #{:T} #{:N} #{:I}]
      "andr.trojan.zsone" [#{:P} #{:T} #{:N}]
      "andr.wandt" [#{:P} #{:N}]
      "andr/bbridge-f" [#{:P} #{:N} #{:I}]
      "android lovetrap" [#{:P} #{:N}]
      "android-trojan/pirates" [#{:P} #{:T} #{:N}]
      "android.adrd" [#{:P} #{:N}]
      "android.adsware.tapjoyads" [#{:P} #{:T} #{:N}]
      "android.backdoor.4" [#{:P} #{:T} #{:I}]
      "android.ddlight" [#{:P} #{:N}]
      "android.exploit.gingerbreak.b" [#{:P} #{:T} #{:N} #{:I}]
      "android.fakeplayer.b" [#{:P} #{:N} #{:I}]
      "android.droidkungfu.origin" [#{:P} #{:N} #{:I}]
      "android.kungfu.a (suspicious)" [#{:P} #{:N} #{:I} #{:I}]
      "android.legana.a" [#{:P} #{:N} #{:I}]
      "android.plankton.6.origin" [#{:P} #{:N} #{:I} #{:I}]
      "android.s.fakeplayer.12927" [#{:P} #{:I} #{:N} #{:I}]
      "android.smsforward.1" [#{:P} #{:N} #{:I}]
      "android.spitmo" [#{:P} #{:N}]
      "android.troj.geinimi.b.v.(kcloud)" [#{:P} #{:T} #{:N} #{:I} #{:I} #{:I}]
      "android.troj.lotoor.b.(kcloud)" [#{:P} #{:T} #{:N} #{:I} #{:I}]
      "android.trojan.adrd.a (b)" [#{:P} #{:T} #{:N} #{:I} #{:I}]
      "android.trojan.droidkungfu.l" [#{:P} #{:T} #{:N} #{:I}]
      "android.trojan.kmin.a" [#{:P} #{:T} #{:N} #{:I}]
      "android.trojan.pjapps.b" [#{:P} #{:T} #{:N} #{:I}]
      "android.trojansms.agent.e" [#{:P} #{:T} #{:I} #{:I}]
      "android/adrd.a.102" [#{:P} #{:N} #{:I} #{:I}]
      "android/androidos_replicator.a" [#{:P} #{:P} #{:N} #{:I}]
      "android/basebridge" [#{:P} #{:N}]
      "android/cve11-1823.c" [#{:P} #{:I} #{:I} #{:I}]
      "android/drad" [#{:P} #{:N}]
      "android/drad.b" [#{:P} #{:N} #{:I}]
      "android/droidkungfu.cz!tr" [#{:P} #{:N} #{:I :T} #{:I}]
      "android/droidkungfu.m.gen" [#{:P} #{:N} #{:I} #{:I}]
      "android/fakeplayer.c" [#{:P} #{:N} #{:I}]
      "android/gappusin.a" [#{:P} #{:N} #{:I}]
      "android/gingermaster" [#{:P} #{:N}]
      "android/golddream.ai!tr.spy" [#{:P} #{:N} #{:I} #{:I} #{:T}]
      "android/gonesixty.a" [#{:P} #{:N} #{:I}]
      "android/h" [#{:P} #{:I}]
      "android/lightdd.a" [#{:P} #{:N} #{:I}]
      "android/lotoor!exploit.cve2010easy" [#{:P} #{:N} #{:T} #{:I}]
      "android/spitmo" [#{:P} #{:N}]
      "android/spy.adrd.a.gen" [#{:P} #{:T} #{:N} #{:I} #{:I}]
      "android/spy.gonesixty.b" [#{:P} #{:T} #{:N} #{:I}]
      "android/yzhc.a.gen" [#{:P} #{:N} #{:I} #{:I}]
      "android:bgserv-b" [#{:P} #{:N} #{:I}]
      "android_mc.bbh" [#{:P} #{:I :T} #{:I :T :N}]
      "androidos.basebridge" [#{:P} #{:N}]
      "androidos.trojan-spy.geimini" [#{:P} #{:T} #{:T} #{:N}]
      "androidos/droidkungfu.c" [#{:P} #{:N} #{:I}]
      "androidos/fakeplayer.a" [#{:P} #{:N} #{:I}]
      "androidos/geimini.htbuaob" [#{:P} #{:N} #{:I :T}]
      "androidos/genbl.5e26403a!olympus" [#{:P} #{:N} #{:I} #{:I}]
      "androidos/pjapps" [#{:P} #{:N}]
      "androidos_gone.b" [#{:P} #{:N} #{:I}]
      "artemis!616a94fbbfb6" [#{:N} #{:I}]
      "artemis!839c37f3a2c8" [#{:N} #{:I}]
      "backdoor trojan" [#{:T} #{:T}]
      "backdoor.androidos.kungfu.fv" [#{:T} #{:P} #{:N} #{:I}]
      "backdoor.androidos.kungfu.hg" [#{:T} #{:P} #{:N} #{:I}]
      "backdoor.generic_c.epk" [#{:T} #{:I} #{:I} #{:I :P :N}]
      "backdoor/androidos.meh" [#{:T} #{:P} #{:I :N}]
      "backdoor/androidos.xsider" [#{:T} #{:P} #{:N}]
      "bds.rooter.i" [#{:I :P :T} #{:N} #{:I}]
      "droidkungfu" [#{:N}]
      "elf/backdoor.tyip-" [#{:P} #{:T} #{:N}]
      "elf/trojan.fccn-10" [#{:P} #{:T} #{:I :N} #{:I}]
      "exploit-android-lotoor" [#{:T} #{:P} #{:N}]
      "exploit.android.tattoohack.a (b)" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "exploit.android.tattoohack.a" [#{:T} #{:P} #{:N} #{:I}]
      "exploit.linux.lotoor (v)" [#{:T} #{:P} #{:N} #{:I}]
      "exploit.linux.lotoor.g" [#{:T} #{:P} #{:N} #{:I}]
      "exploit:androidos/cve-2011-1823" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "generic trojan" [#{:I} #{:T}]
      "generic.gu" [#{:I} #{:I :P :T}]
      "heur:backdoor.androidos.kungfu.a" [#{:I} #{:T} #{:P} #{:N} #{:I}]
      "heur:trojan-sms.androidos.hispo.a" [#{:I} #{:T} #{:I} #{:P} #{:N} #{:I}]
      "js.a.iframe.4787.a" [#{:P} #{:I} #{:P} #{:I} #{:I}]
      "linux.s.ex-lotoor.1655575" [#{:P} #{:I} #{:I} #{:N} #{:I}]
      "monitoring-tool:android/mobismsspy.a!mfb" [#{:I} #{:T} #{:P} #{:N} #{:I} #{:I}]
      "monitoring-tool:android/mobismsspy.a" [#{:I} #{:T} #{:P} #{:N} #{:I}]
      "mw.clod609.trojan.6cc4" [#{:I :P} #{:I :P} #{:T} #{:I :P}]
      "not-a-virus:heur:monitor.androidos.gams.a" [#{:I} #{:I} #{:T} #{:I} #{:T} #{:P} #{:N} #{:I}]
      "not-a-virus:monitor.androidos.mobinauten" [#{:I} #{:I} #{:T} #{:T} #{:P} #{:N}]
      "not-a-virus:monitor.androidos.mobinauten.c" [#{:I} #{:I} #{:T} #{:T} #{:P} #{:N} #{:I}]
      "possiblethreat" [#{:I}]
      "replicator.a" [#{:N} #{:I}]
      "riskware/gpspy!android" [#{:T} #{:N} #{:P}]
      "spy.androidos" [#{:T} #{:P}]
      "spyware:android/sndapps" [#{:T} #{:P} #{:N}]
      "suspicious_gen2.sjmdx" [#{:I} #{:I :P} #{:I :P :T :N}]
      "tr/agent.389386" [#{:I} #{:I} #{:I}]
      "tr/expl.linux.lotoor.m" [#{:I} #{:T} #{:P} #{:N} #{:I}]
      "tr/spy.geimini.b" [#{:I} #{:T} #{:N} #{:I}]
      "troj.generic.(kcloud)" [#{:T} #{:I} #{:I}]
      "troj.unknow.a.(kcloud)" [#{:T} #{:N} #{:I} #{:I}]
      "troj_gen.rcbohl8" [#{:T} #{:I} #{:I :P}]
      "trojan horse" [#{:T} #{:T}]
      "trojan" [#{:T}]
      "trojan-downloader.androidos.dordrae.cf" [#{:T} #{:T} #{:P} #{:N} #{:I}]
      "trojan-pws.androidos.fakenefix" [#{:T} #{:T} #{:P} #{:N}]
      "trojan-sms.androidos.raden.f" [#{:T} #{:I} #{:P} #{:N} #{:I}]
      "trojan-spy.androidos.adrd.e" [#{:T} #{:T} #{:P} #{:N} #{:I}]
      "trojan-spy.androidos.geinimi" [#{:T} #{:T} #{:P} #{:N}]
      "trojan.agent.fxy" [#{:T} #{:I} #{:I :P :N}]
      "trojan.android.spy.gasms.a" [#{:T} #{:P} #{:T} #{:N} #{:I}]
      "trojan.androidos.anserver" [#{:T} #{:P} #{:N}]
      "trojan.androidos.ddlight.b" [#{:T} #{:P} #{:N} #{:I}]
      "trojan.androidos.ddream.b.gen" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "trojan.androidos.droidkungfu.c (v)" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "trojan.androidos.plangton.i" [#{:T} #{:P} #{:N} #{:I}]
      "trojan.androidos.uxipp" [#{:T} #{:P} #{:N}]
      "trojan.androidos.walkinwat.a" [#{:T} #{:P} #{:N} #{:I}]
      "trojan.dl.androidos.dordrae.a" [#{:T} #{:I} #{:P} #{:N} #{:I}]
      "trojan.fhgf-9" [#{:T} #{:I :P :N} #{:I}]
      "trojan.gen.2" [#{:T} #{:I} #{:I}]
      "trojan.linux.a.ex-lotoor.14028" [#{:T} #{:P} #{:I} #{:I} #{:N} #{:I}]
      "trojan.pjapps.bdokty" [#{:T} #{:N} #{:I :P}]
      "trojan.spy.lightdd!5537" [#{:T} #{:T} #{:N} #{:I}]
      "trojan.unix.androidsmsspy.a" [#{:T} #{:P} #{:N} #{:I}]
      "trojan.win32.java.undef.d" [#{:T} #{:P} #{:P} #{:I} #{:I}]
      "trojan:android/fakeneflic.a" [#{:T} #{:P} #{:N} #{:I}]
      "trojan:android/pjapps.b!mfb" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "trojan:androidos/anserver.a" [#{:T} #{:P} #{:N} #{:I}]
      "trojan:androidos/raden.gen!a" [#{:T} #{:P} #{:N} #{:I} #{:I}]
      "trojan:linux/droidkrungfu" [#{:T} #{:P} #{:N}]
      "trojanspy.androidos.ao" [#{:T} #{:P} #{:I}]
      "trojware.android.spy.adrd.af" [#{:T} #{:P} #{:T} #{:N} #{:I}]
      "trojware.spy.unclassifiedmalware" [#{:T} #{:T} #{:T}]
      "trojware.win32.agent.~aot" [#{:T} #{:P} #{:I} #{:I :N}]
      "unclassifiedmalware" [#{:T}]
      "unix/lotoor" [#{:P} #{:N}]
      "virus_unknown" [#{:T} #{:I}]
      "w32/malware_fam.nb" [#{:P} #{:T} #{:I :N} #{:I}]
      "w32/pjapps" [#{:P} #{:N}]
      "win32.android.geinim" [#{:P} #{:P} #{:N}]
      "win32.horse" [#{:P} #{:T}])))
